sudo: required
services:
  - docker

before_install:
  - docker build -t dstafford/docker-madness -f Dockerfile.dev .

script:
  - docker run -e CI=true dstafford/docker-madness yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockermandess"
  env: "DockerMandess-env"
  bucket_name: "elasticbeanstalk-us-east-2-844337442446"
  bucket_path: "dockermandess"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
